export const UPDATE_AUTHENTICATION = 'UPDATE_AUTHENTICATION';
export const UPDATE_BALANCES = 'UPDATE_BALANCES';
export const UPDATE_TICKERS = 'UPDATE_TICKERS';
export const UPDATE_TRADE_HISTORIES = 'UPDATE_TRADE_HISTORIES';
export const UPDATE_OPEN_ORDERS = 'UPDATE_OPEN_ORDERS';
export const UPDATE_APPLICATION_SETTINGS = 'UPDATE_APPLICATION_SETTINGS';
// assets
export const UPDATE_ASSET_SETTINGS = 'UPDATE_ASSET_SETTINGS';
export const SET_DEFAULT_ASSET_SETTINGS = 'SET_DEFAULT_ASSET_SETTINGS';
// Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
