export const UPDATE_AUTHENTICATION = 'UPDATE_AUTHENTICATION';
export const UPDATE_BALANCES = 'UPDATE_BALANCES';
export const UPDATE_TICKERS = 'UPDATE_TICKERS';
// assets
export const UPDATE_ASSET_SETTINGS = 'UPDATE_ASSET_SETTINGS';
export const SET_DEFAULT_ASSET_SETTINGS = 'SET_DEFAULT_ASSET_SETTINGS';
