export const UPDATE_AUTHENTICATION = 'UPDATE_AUTHENTICATION';
export const UPDATE_BALANCES = 'UPDATE_BALANCES';
export const UPDATE_TICKER = 'UPDATE_TICKER';
export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO';
